/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteDotwebmanifestRouteImport } from './routes/site[.]webmanifest'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IconDotsvgRouteImport } from './routes/icon[.]svg'
import { Route as IconMaskableDotsvgRouteImport } from './routes/icon-maskable[.]svg'
import { Route as AppleTouchIconDotpngRouteImport } from './routes/apple-touch-icon[.]png'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}.index'
import { Route as Char123LocaleChar125PuntosRouteImport } from './routes/{-$locale}.puntos'
import { Route as Char123LocaleChar125PrivacidadRouteImport } from './routes/{-$locale}.privacidad'
import { Route as Char123LocaleChar125OfflineRouteImport } from './routes/{-$locale}.offline'
import { Route as Char123LocaleChar125DestacadosRouteImport } from './routes/{-$locale}.destacados'
import { Route as Char123LocaleChar125ContactoRouteImport } from './routes/{-$locale}.contacto'
import { Route as Char123LocaleChar125AvisoLegalRouteImport } from './routes/{-$locale}.aviso-legal'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteDotwebmanifestRoute = SiteDotwebmanifestRouteImport.update({
  id: '/site.webmanifest',
  path: '/site.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IconDotsvgRoute = IconDotsvgRouteImport.update({
  id: '/icon.svg',
  path: '/icon.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const IconMaskableDotsvgRoute = IconMaskableDotsvgRouteImport.update({
  id: '/icon-maskable.svg',
  path: '/icon-maskable.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const AppleTouchIconDotpngRoute = AppleTouchIconDotpngRouteImport.update({
  id: '/apple-touch-icon.png',
  path: '/apple-touch-icon.png',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125PuntosRoute =
  Char123LocaleChar125PuntosRouteImport.update({
    id: '/puntos',
    path: '/puntos',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125PrivacidadRoute =
  Char123LocaleChar125PrivacidadRouteImport.update({
    id: '/privacidad',
    path: '/privacidad',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125OfflineRoute =
  Char123LocaleChar125OfflineRouteImport.update({
    id: '/offline',
    path: '/offline',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125DestacadosRoute =
  Char123LocaleChar125DestacadosRouteImport.update({
    id: '/destacados',
    path: '/destacados',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ContactoRoute =
  Char123LocaleChar125ContactoRouteImport.update({
    id: '/contacto',
    path: '/contacto',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AvisoLegalRoute =
  Char123LocaleChar125AvisoLegalRouteImport.update({
    id: '/aviso-legal',
    path: '/aviso-legal',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/apple-touch-icon.png': typeof AppleTouchIconDotpngRoute
  '/icon-maskable.svg': typeof IconMaskableDotsvgRoute
  '/icon.svg': typeof IconDotsvgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/aviso-legal': typeof Char123LocaleChar125AvisoLegalRoute
  '/{-$locale}/contacto': typeof Char123LocaleChar125ContactoRoute
  '/{-$locale}/destacados': typeof Char123LocaleChar125DestacadosRoute
  '/{-$locale}/offline': typeof Char123LocaleChar125OfflineRoute
  '/{-$locale}/privacidad': typeof Char123LocaleChar125PrivacidadRoute
  '/{-$locale}/puntos': typeof Char123LocaleChar125PuntosRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesByTo {
  '/apple-touch-icon.png': typeof AppleTouchIconDotpngRoute
  '/icon-maskable.svg': typeof IconMaskableDotsvgRoute
  '/icon.svg': typeof IconDotsvgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/aviso-legal': typeof Char123LocaleChar125AvisoLegalRoute
  '/{-$locale}/contacto': typeof Char123LocaleChar125ContactoRoute
  '/{-$locale}/destacados': typeof Char123LocaleChar125DestacadosRoute
  '/{-$locale}/offline': typeof Char123LocaleChar125OfflineRoute
  '/{-$locale}/privacidad': typeof Char123LocaleChar125PrivacidadRoute
  '/{-$locale}/puntos': typeof Char123LocaleChar125PuntosRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/apple-touch-icon.png': typeof AppleTouchIconDotpngRoute
  '/icon-maskable.svg': typeof IconMaskableDotsvgRoute
  '/icon.svg': typeof IconDotsvgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/aviso-legal': typeof Char123LocaleChar125AvisoLegalRoute
  '/{-$locale}/contacto': typeof Char123LocaleChar125ContactoRoute
  '/{-$locale}/destacados': typeof Char123LocaleChar125DestacadosRoute
  '/{-$locale}/offline': typeof Char123LocaleChar125OfflineRoute
  '/{-$locale}/privacidad': typeof Char123LocaleChar125PrivacidadRoute
  '/{-$locale}/puntos': typeof Char123LocaleChar125PuntosRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/apple-touch-icon.png'
    | '/icon-maskable.svg'
    | '/icon.svg'
    | '/robots.txt'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/{-$locale}/aviso-legal'
    | '/{-$locale}/contacto'
    | '/{-$locale}/destacados'
    | '/{-$locale}/offline'
    | '/{-$locale}/privacidad'
    | '/{-$locale}/puntos'
    | '/{-$locale}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/apple-touch-icon.png'
    | '/icon-maskable.svg'
    | '/icon.svg'
    | '/robots.txt'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/{-$locale}/aviso-legal'
    | '/{-$locale}/contacto'
    | '/{-$locale}/destacados'
    | '/{-$locale}/offline'
    | '/{-$locale}/privacidad'
    | '/{-$locale}/puntos'
    | '/{-$locale}'
  id:
    | '__root__'
    | '/apple-touch-icon.png'
    | '/icon-maskable.svg'
    | '/icon.svg'
    | '/robots.txt'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/{-$locale}/aviso-legal'
    | '/{-$locale}/contacto'
    | '/{-$locale}/destacados'
    | '/{-$locale}/offline'
    | '/{-$locale}/privacidad'
    | '/{-$locale}/puntos'
    | '/{-$locale}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppleTouchIconDotpngRoute: typeof AppleTouchIconDotpngRoute
  IconMaskableDotsvgRoute: typeof IconMaskableDotsvgRoute
  IconDotsvgRoute: typeof IconDotsvgRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SiteDotwebmanifestRoute: typeof SiteDotwebmanifestRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site.webmanifest': {
      id: '/site.webmanifest'
      path: '/site.webmanifest'
      fullPath: '/site.webmanifest'
      preLoaderRoute: typeof SiteDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icon.svg': {
      id: '/icon.svg'
      path: '/icon.svg'
      fullPath: '/icon.svg'
      preLoaderRoute: typeof IconDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icon-maskable.svg': {
      id: '/icon-maskable.svg'
      path: '/icon-maskable.svg'
      fullPath: '/icon-maskable.svg'
      preLoaderRoute: typeof IconMaskableDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apple-touch-icon.png': {
      id: '/apple-touch-icon.png'
      path: '/apple-touch-icon.png'
      fullPath: '/apple-touch-icon.png'
      preLoaderRoute: typeof AppleTouchIconDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/puntos': {
      id: '/{-$locale}/puntos'
      path: '/puntos'
      fullPath: '/{-$locale}/puntos'
      preLoaderRoute: typeof Char123LocaleChar125PuntosRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/privacidad': {
      id: '/{-$locale}/privacidad'
      path: '/privacidad'
      fullPath: '/{-$locale}/privacidad'
      preLoaderRoute: typeof Char123LocaleChar125PrivacidadRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/offline': {
      id: '/{-$locale}/offline'
      path: '/offline'
      fullPath: '/{-$locale}/offline'
      preLoaderRoute: typeof Char123LocaleChar125OfflineRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/destacados': {
      id: '/{-$locale}/destacados'
      path: '/destacados'
      fullPath: '/{-$locale}/destacados'
      preLoaderRoute: typeof Char123LocaleChar125DestacadosRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/contacto': {
      id: '/{-$locale}/contacto'
      path: '/contacto'
      fullPath: '/{-$locale}/contacto'
      preLoaderRoute: typeof Char123LocaleChar125ContactoRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/aviso-legal': {
      id: '/{-$locale}/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/{-$locale}/aviso-legal'
      preLoaderRoute: typeof Char123LocaleChar125AvisoLegalRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
  }
}

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125AvisoLegalRoute: typeof Char123LocaleChar125AvisoLegalRoute
  Char123LocaleChar125ContactoRoute: typeof Char123LocaleChar125ContactoRoute
  Char123LocaleChar125DestacadosRoute: typeof Char123LocaleChar125DestacadosRoute
  Char123LocaleChar125OfflineRoute: typeof Char123LocaleChar125OfflineRoute
  Char123LocaleChar125PrivacidadRoute: typeof Char123LocaleChar125PrivacidadRoute
  Char123LocaleChar125PuntosRoute: typeof Char123LocaleChar125PuntosRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125AvisoLegalRoute: Char123LocaleChar125AvisoLegalRoute,
  Char123LocaleChar125ContactoRoute: Char123LocaleChar125ContactoRoute,
  Char123LocaleChar125DestacadosRoute: Char123LocaleChar125DestacadosRoute,
  Char123LocaleChar125OfflineRoute: Char123LocaleChar125OfflineRoute,
  Char123LocaleChar125PrivacidadRoute: Char123LocaleChar125PrivacidadRoute,
  Char123LocaleChar125PuntosRoute: Char123LocaleChar125PuntosRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppleTouchIconDotpngRoute: AppleTouchIconDotpngRoute,
  IconMaskableDotsvgRoute: IconMaskableDotsvgRoute,
  IconDotsvgRoute: IconDotsvgRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SiteDotwebmanifestRoute: SiteDotwebmanifestRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
