/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthThemeRouteImport } from './routes/_auth.theme'
import { Route as AuthPromotionsRouteImport } from './routes/_auth.promotions'
import { Route as AuthMenuRouteImport } from './routes/_auth.menu'
import { Route as AuthLanguagesRouteImport } from './routes/_auth.languages'
import { Route as AuthBranchRouteImport } from './routes/_auth.branch'
import { Route as AuthBillingRouteImport } from './routes/_auth.billing'
import { Route as AuthPromotionsIndexRouteImport } from './routes/_auth.promotions.index'
import { Route as AuthMenuIndexRouteImport } from './routes/_auth.menu.index'
import { Route as AuthLanguagesIndexRouteImport } from './routes/_auth.languages.index'
import { Route as AuthPromotionsNewRouteImport } from './routes/_auth.promotions.new'
import { Route as AuthPromotionsPromotionIdRouteImport } from './routes/_auth.promotions.$promotionId'
import { Route as AuthLanguagesLanguageCodeRouteImport } from './routes/_auth.languages.$languageCode'
import { Route as AuthMenuDishesNewRouteImport } from './routes/_auth.menu.dishes.new'
import { Route as AuthMenuDishesDishIdRouteImport } from './routes/_auth.menu.dishes.$dishId'
import { Route as AuthMenuCategoriesNewRouteImport } from './routes/_auth.menu.categories.new'
import { Route as AuthMenuCategoriesCategoryIdRouteImport } from './routes/_auth.menu.categories.$categoryId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthThemeRoute = AuthThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPromotionsRoute = AuthPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMenuRoute = AuthMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLanguagesRoute = AuthLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBranchRoute = AuthBranchRouteImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBillingRoute = AuthBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPromotionsIndexRoute = AuthPromotionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPromotionsRoute,
} as any)
const AuthMenuIndexRoute = AuthMenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthMenuRoute,
} as any)
const AuthLanguagesIndexRoute = AuthLanguagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLanguagesRoute,
} as any)
const AuthPromotionsNewRoute = AuthPromotionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthPromotionsRoute,
} as any)
const AuthPromotionsPromotionIdRoute =
  AuthPromotionsPromotionIdRouteImport.update({
    id: '/$promotionId',
    path: '/$promotionId',
    getParentRoute: () => AuthPromotionsRoute,
  } as any)
const AuthLanguagesLanguageCodeRoute =
  AuthLanguagesLanguageCodeRouteImport.update({
    id: '/$languageCode',
    path: '/$languageCode',
    getParentRoute: () => AuthLanguagesRoute,
  } as any)
const AuthMenuDishesNewRoute = AuthMenuDishesNewRouteImport.update({
  id: '/dishes/new',
  path: '/dishes/new',
  getParentRoute: () => AuthMenuRoute,
} as any)
const AuthMenuDishesDishIdRoute = AuthMenuDishesDishIdRouteImport.update({
  id: '/dishes/$dishId',
  path: '/dishes/$dishId',
  getParentRoute: () => AuthMenuRoute,
} as any)
const AuthMenuCategoriesNewRoute = AuthMenuCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => AuthMenuRoute,
} as any)
const AuthMenuCategoriesCategoryIdRoute =
  AuthMenuCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => AuthMenuRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AuthBillingRoute
  '/branch': typeof AuthBranchRoute
  '/languages': typeof AuthLanguagesRouteWithChildren
  '/menu': typeof AuthMenuRouteWithChildren
  '/promotions': typeof AuthPromotionsRouteWithChildren
  '/theme': typeof AuthThemeRoute
  '/languages/$languageCode': typeof AuthLanguagesLanguageCodeRoute
  '/promotions/$promotionId': typeof AuthPromotionsPromotionIdRoute
  '/promotions/new': typeof AuthPromotionsNewRoute
  '/languages/': typeof AuthLanguagesIndexRoute
  '/menu/': typeof AuthMenuIndexRoute
  '/promotions/': typeof AuthPromotionsIndexRoute
  '/menu/categories/$categoryId': typeof AuthMenuCategoriesCategoryIdRoute
  '/menu/categories/new': typeof AuthMenuCategoriesNewRoute
  '/menu/dishes/$dishId': typeof AuthMenuDishesDishIdRoute
  '/menu/dishes/new': typeof AuthMenuDishesNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/billing': typeof AuthBillingRoute
  '/branch': typeof AuthBranchRoute
  '/theme': typeof AuthThemeRoute
  '/': typeof AuthIndexRoute
  '/languages/$languageCode': typeof AuthLanguagesLanguageCodeRoute
  '/promotions/$promotionId': typeof AuthPromotionsPromotionIdRoute
  '/promotions/new': typeof AuthPromotionsNewRoute
  '/languages': typeof AuthLanguagesIndexRoute
  '/menu': typeof AuthMenuIndexRoute
  '/promotions': typeof AuthPromotionsIndexRoute
  '/menu/categories/$categoryId': typeof AuthMenuCategoriesCategoryIdRoute
  '/menu/categories/new': typeof AuthMenuCategoriesNewRoute
  '/menu/dishes/$dishId': typeof AuthMenuDishesDishIdRoute
  '/menu/dishes/new': typeof AuthMenuDishesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/billing': typeof AuthBillingRoute
  '/_auth/branch': typeof AuthBranchRoute
  '/_auth/languages': typeof AuthLanguagesRouteWithChildren
  '/_auth/menu': typeof AuthMenuRouteWithChildren
  '/_auth/promotions': typeof AuthPromotionsRouteWithChildren
  '/_auth/theme': typeof AuthThemeRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/languages/$languageCode': typeof AuthLanguagesLanguageCodeRoute
  '/_auth/promotions/$promotionId': typeof AuthPromotionsPromotionIdRoute
  '/_auth/promotions/new': typeof AuthPromotionsNewRoute
  '/_auth/languages/': typeof AuthLanguagesIndexRoute
  '/_auth/menu/': typeof AuthMenuIndexRoute
  '/_auth/promotions/': typeof AuthPromotionsIndexRoute
  '/_auth/menu/categories/$categoryId': typeof AuthMenuCategoriesCategoryIdRoute
  '/_auth/menu/categories/new': typeof AuthMenuCategoriesNewRoute
  '/_auth/menu/dishes/$dishId': typeof AuthMenuDishesDishIdRoute
  '/_auth/menu/dishes/new': typeof AuthMenuDishesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/billing'
    | '/branch'
    | '/languages'
    | '/menu'
    | '/promotions'
    | '/theme'
    | '/languages/$languageCode'
    | '/promotions/$promotionId'
    | '/promotions/new'
    | '/languages/'
    | '/menu/'
    | '/promotions/'
    | '/menu/categories/$categoryId'
    | '/menu/categories/new'
    | '/menu/dishes/$dishId'
    | '/menu/dishes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/billing'
    | '/branch'
    | '/theme'
    | '/'
    | '/languages/$languageCode'
    | '/promotions/$promotionId'
    | '/promotions/new'
    | '/languages'
    | '/menu'
    | '/promotions'
    | '/menu/categories/$categoryId'
    | '/menu/categories/new'
    | '/menu/dishes/$dishId'
    | '/menu/dishes/new'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/billing'
    | '/_auth/branch'
    | '/_auth/languages'
    | '/_auth/menu'
    | '/_auth/promotions'
    | '/_auth/theme'
    | '/_auth/'
    | '/_auth/languages/$languageCode'
    | '/_auth/promotions/$promotionId'
    | '/_auth/promotions/new'
    | '/_auth/languages/'
    | '/_auth/menu/'
    | '/_auth/promotions/'
    | '/_auth/menu/categories/$categoryId'
    | '/_auth/menu/categories/new'
    | '/_auth/menu/dishes/$dishId'
    | '/_auth/menu/dishes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/theme': {
      id: '/_auth/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof AuthThemeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/promotions': {
      id: '/_auth/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthPromotionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/menu': {
      id: '/_auth/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthMenuRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/languages': {
      id: '/_auth/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof AuthLanguagesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/branch': {
      id: '/_auth/branch'
      path: '/branch'
      fullPath: '/branch'
      preLoaderRoute: typeof AuthBranchRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/billing': {
      id: '/_auth/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthBillingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/promotions/': {
      id: '/_auth/promotions/'
      path: '/'
      fullPath: '/promotions/'
      preLoaderRoute: typeof AuthPromotionsIndexRouteImport
      parentRoute: typeof AuthPromotionsRoute
    }
    '/_auth/menu/': {
      id: '/_auth/menu/'
      path: '/'
      fullPath: '/menu/'
      preLoaderRoute: typeof AuthMenuIndexRouteImport
      parentRoute: typeof AuthMenuRoute
    }
    '/_auth/languages/': {
      id: '/_auth/languages/'
      path: '/'
      fullPath: '/languages/'
      preLoaderRoute: typeof AuthLanguagesIndexRouteImport
      parentRoute: typeof AuthLanguagesRoute
    }
    '/_auth/promotions/new': {
      id: '/_auth/promotions/new'
      path: '/new'
      fullPath: '/promotions/new'
      preLoaderRoute: typeof AuthPromotionsNewRouteImport
      parentRoute: typeof AuthPromotionsRoute
    }
    '/_auth/promotions/$promotionId': {
      id: '/_auth/promotions/$promotionId'
      path: '/$promotionId'
      fullPath: '/promotions/$promotionId'
      preLoaderRoute: typeof AuthPromotionsPromotionIdRouteImport
      parentRoute: typeof AuthPromotionsRoute
    }
    '/_auth/languages/$languageCode': {
      id: '/_auth/languages/$languageCode'
      path: '/$languageCode'
      fullPath: '/languages/$languageCode'
      preLoaderRoute: typeof AuthLanguagesLanguageCodeRouteImport
      parentRoute: typeof AuthLanguagesRoute
    }
    '/_auth/menu/dishes/new': {
      id: '/_auth/menu/dishes/new'
      path: '/dishes/new'
      fullPath: '/menu/dishes/new'
      preLoaderRoute: typeof AuthMenuDishesNewRouteImport
      parentRoute: typeof AuthMenuRoute
    }
    '/_auth/menu/dishes/$dishId': {
      id: '/_auth/menu/dishes/$dishId'
      path: '/dishes/$dishId'
      fullPath: '/menu/dishes/$dishId'
      preLoaderRoute: typeof AuthMenuDishesDishIdRouteImport
      parentRoute: typeof AuthMenuRoute
    }
    '/_auth/menu/categories/new': {
      id: '/_auth/menu/categories/new'
      path: '/categories/new'
      fullPath: '/menu/categories/new'
      preLoaderRoute: typeof AuthMenuCategoriesNewRouteImport
      parentRoute: typeof AuthMenuRoute
    }
    '/_auth/menu/categories/$categoryId': {
      id: '/_auth/menu/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/menu/categories/$categoryId'
      preLoaderRoute: typeof AuthMenuCategoriesCategoryIdRouteImport
      parentRoute: typeof AuthMenuRoute
    }
  }
}

interface AuthLanguagesRouteChildren {
  AuthLanguagesLanguageCodeRoute: typeof AuthLanguagesLanguageCodeRoute
  AuthLanguagesIndexRoute: typeof AuthLanguagesIndexRoute
}

const AuthLanguagesRouteChildren: AuthLanguagesRouteChildren = {
  AuthLanguagesLanguageCodeRoute: AuthLanguagesLanguageCodeRoute,
  AuthLanguagesIndexRoute: AuthLanguagesIndexRoute,
}

const AuthLanguagesRouteWithChildren = AuthLanguagesRoute._addFileChildren(
  AuthLanguagesRouteChildren,
)

interface AuthMenuRouteChildren {
  AuthMenuIndexRoute: typeof AuthMenuIndexRoute
  AuthMenuCategoriesCategoryIdRoute: typeof AuthMenuCategoriesCategoryIdRoute
  AuthMenuCategoriesNewRoute: typeof AuthMenuCategoriesNewRoute
  AuthMenuDishesDishIdRoute: typeof AuthMenuDishesDishIdRoute
  AuthMenuDishesNewRoute: typeof AuthMenuDishesNewRoute
}

const AuthMenuRouteChildren: AuthMenuRouteChildren = {
  AuthMenuIndexRoute: AuthMenuIndexRoute,
  AuthMenuCategoriesCategoryIdRoute: AuthMenuCategoriesCategoryIdRoute,
  AuthMenuCategoriesNewRoute: AuthMenuCategoriesNewRoute,
  AuthMenuDishesDishIdRoute: AuthMenuDishesDishIdRoute,
  AuthMenuDishesNewRoute: AuthMenuDishesNewRoute,
}

const AuthMenuRouteWithChildren = AuthMenuRoute._addFileChildren(
  AuthMenuRouteChildren,
)

interface AuthPromotionsRouteChildren {
  AuthPromotionsPromotionIdRoute: typeof AuthPromotionsPromotionIdRoute
  AuthPromotionsNewRoute: typeof AuthPromotionsNewRoute
  AuthPromotionsIndexRoute: typeof AuthPromotionsIndexRoute
}

const AuthPromotionsRouteChildren: AuthPromotionsRouteChildren = {
  AuthPromotionsPromotionIdRoute: AuthPromotionsPromotionIdRoute,
  AuthPromotionsNewRoute: AuthPromotionsNewRoute,
  AuthPromotionsIndexRoute: AuthPromotionsIndexRoute,
}

const AuthPromotionsRouteWithChildren = AuthPromotionsRoute._addFileChildren(
  AuthPromotionsRouteChildren,
)

interface AuthRouteChildren {
  AuthBillingRoute: typeof AuthBillingRoute
  AuthBranchRoute: typeof AuthBranchRoute
  AuthLanguagesRoute: typeof AuthLanguagesRouteWithChildren
  AuthMenuRoute: typeof AuthMenuRouteWithChildren
  AuthPromotionsRoute: typeof AuthPromotionsRouteWithChildren
  AuthThemeRoute: typeof AuthThemeRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBillingRoute: AuthBillingRoute,
  AuthBranchRoute: AuthBranchRoute,
  AuthLanguagesRoute: AuthLanguagesRouteWithChildren,
  AuthMenuRoute: AuthMenuRouteWithChildren,
  AuthPromotionsRoute: AuthPromotionsRouteWithChildren,
  AuthThemeRoute: AuthThemeRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
