interface PrintCopy {
  allergens: string;
  extras: string;
  menu: string;
  options: string;
  page: string;
  recommended: string;
  scan: string;
}

const COPY: Record<string, PrintCopy> = {
  ca: {
    allergens: "Al·lèrgens",
    extras: "Extres",
    menu: "Carta",
    options: "Opcions",
    page: "Pàgina",
    recommended: "Recomanat",
    scan: "Escaneja per veure la carta actualitzada",
  },
  de: {
    allergens: "Allergene",
    extras: "Extras",
    menu: "Speisekarte",
    options: "Optionen",
    page: "Seite",
    recommended: "Empfohlen",
    scan: "Für die aktuelle Speisekarte scannen",
  },
  en: {
    allergens: "Allergens",
    extras: "Extras",
    menu: "Menu",
    options: "Options",
    page: "Page",
    recommended: "Recommended",
    scan: "Scan for the latest menu",
  },
  es: {
    allergens: "Alérgenos",
    extras: "Extras",
    menu: "Carta",
    options: "Opciones",
    page: "Página",
    recommended: "Recomendado",
    scan: "Escanea para ver la carta actualizada",
  },
  eu: {
    allergens: "Alergenoak",
    extras: "Gehigarriak",
    menu: "Menua",
    options: "Aukerak",
    page: "Orria",
    recommended: "Gomendatua",
    scan: "Eskaneatu menu eguneratua ikusteko",
  },
  fr: {
    allergens: "Allergènes",
    extras: "Suppléments",
    menu: "Carte",
    options: "Options",
    page: "Page",
    recommended: "Recommandé",
    scan: "Scannez pour voir la carte à jour",
  },
  gl: {
    allergens: "Alérxenos",
    extras: "Extras",
    menu: "Carta",
    options: "Opcións",
    page: "Páxina",
    recommended: "Recomendado",
    scan: "Escanea para ver a carta actualizada",
  },
  it: {
    allergens: "Allergeni",
    extras: "Extra",
    menu: "Menu",
    options: "Opzioni",
    page: "Pagina",
    recommended: "Consigliato",
    scan: "Scansiona per il menu aggiornato",
  },
  nl: {
    allergens: "Allergenen",
    extras: "Extra's",
    menu: "Menu",
    options: "Opties",
    page: "Pagina",
    recommended: "Aanbevolen",
    scan: "Scan voor het actuele menu",
  },
  pl: {
    allergens: "Alergeny",
    extras: "Dodatki",
    menu: "Menu",
    options: "Opcje",
    page: "Strona",
    recommended: "Polecane",
    scan: "Zeskanuj, aby zobaczyć aktualne menu",
  },
  pt: {
    allergens: "Alergénios",
    extras: "Extras",
    menu: "Menu",
    options: "Opções",
    page: "Página",
    recommended: "Recomendado",
    scan: "Digitalize para ver o menu atualizado",
  },
};

const ALLERGEN_LABELS: Record<string, Record<string, string>> = {
  ca: {
    celery: "api",
    crustaceans: "crustacis",
    eggs: "ous",
    fish: "peix",
    gluten: "gluten",
    lupin: "tramussos",
    milk: "llet",
    molluscs: "mol·luscs",
    mustard: "mostassa",
    nuts: "fruits de closca",
    peanuts: "cacauets",
    sesame: "sèsam",
    soybeans: "soja",
    sulphites: "sulfits",
  },
  de: {
    celery: "Sellerie",
    crustaceans: "Krebstiere",
    eggs: "Eier",
    fish: "Fisch",
    gluten: "Gluten",
    lupin: "Lupinen",
    milk: "Milch",
    molluscs: "Weichtiere",
    mustard: "Senf",
    nuts: "Schalenfrüchte",
    peanuts: "Erdnüsse",
    sesame: "Sesam",
    soybeans: "Soja",
    sulphites: "Sulfite",
  },
  en: {
    celery: "celery",
    crustaceans: "crustaceans",
    eggs: "eggs",
    fish: "fish",
    gluten: "gluten",
    lupin: "lupin",
    milk: "milk",
    molluscs: "molluscs",
    mustard: "mustard",
    nuts: "nuts",
    peanuts: "peanuts",
    sesame: "sesame",
    soybeans: "soybeans",
    sulphites: "sulphites",
  },
  es: {
    celery: "apio",
    crustaceans: "crustáceos",
    eggs: "huevo",
    fish: "pescado",
    gluten: "gluten",
    lupin: "altramuces",
    milk: "lácteos",
    molluscs: "moluscos",
    mustard: "mostaza",
    nuts: "frutos secos",
    peanuts: "cacahuetes",
    sesame: "sésamo",
    soybeans: "soja",
    sulphites: "sulfitos",
  },
  eu: {
    celery: "apioa",
    crustaceans: "krustazeoak",
    eggs: "arrautzak",
    fish: "arraina",
    gluten: "glutena",
    lupin: "eskuzuria",
    milk: "esnea",
    molluscs: "moluskuak",
    mustard: "ziapea",
    nuts: "fruitu lehorrak",
    peanuts: "kakahueteak",
    sesame: "sesamoa",
    soybeans: "soja",
    sulphites: "sulfitoak",
  },
  fr: {
    celery: "céleri",
    crustaceans: "crustacés",
    eggs: "oeufs",
    fish: "poisson",
    gluten: "gluten",
    lupin: "lupin",
    milk: "lait",
    molluscs: "mollusques",
    mustard: "moutarde",
    nuts: "fruits à coque",
    peanuts: "arachides",
    sesame: "sésame",
    soybeans: "soja",
    sulphites: "sulfites",
  },
  gl: {
    celery: "apio",
    crustaceans: "crustáceos",
    eggs: "ovos",
    fish: "peixe",
    gluten: "glute",
    lupin: "altramuces",
    milk: "leite",
    molluscs: "moluscos",
    mustard: "mostaza",
    nuts: "froitos secos",
    peanuts: "cacahuetes",
    sesame: "sésamo",
    soybeans: "soia",
    sulphites: "sulfitos",
  },
  it: {
    celery: "sedano",
    crustaceans: "crostacei",
    eggs: "uova",
    fish: "pesce",
    gluten: "glutine",
    lupin: "lupini",
    milk: "latte",
    molluscs: "molluschi",
    mustard: "senape",
    nuts: "frutta a guscio",
    peanuts: "arachidi",
    sesame: "sesamo",
    soybeans: "soia",
    sulphites: "solfiti",
  },
  nl: {
    celery: "selderij",
    crustaceans: "schaaldieren",
    eggs: "eieren",
    fish: "vis",
    gluten: "gluten",
    lupin: "lupine",
    milk: "melk",
    molluscs: "weekdieren",
    mustard: "mosterd",
    nuts: "noten",
    peanuts: "pinda's",
    sesame: "sesam",
    soybeans: "soja",
    sulphites: "sulfieten",
  },
  pl: {
    celery: "seler",
    crustaceans: "skorupiaki",
    eggs: "jaja",
    fish: "ryby",
    gluten: "gluten",
    lupin: "łubin",
    milk: "mleko",
    molluscs: "mięczaki",
    mustard: "gorczyca",
    nuts: "orzechy",
    peanuts: "orzeszki ziemne",
    sesame: "sezam",
    soybeans: "soja",
    sulphites: "siarczyny",
  },
  pt: {
    celery: "aipo",
    crustaceans: "crustáceos",
    eggs: "ovos",
    fish: "peixe",
    gluten: "glúten",
    lupin: "tremoço",
    milk: "leite",
    molluscs: "moluscos",
    mustard: "mostarda",
    nuts: "frutos de casca rija",
    peanuts: "amendoins",
    sesame: "sésamo",
    soybeans: "soja",
    sulphites: "sulfitos",
  },
};

export function getPrintCopy(locale: string): PrintCopy {
  return COPY[locale] ?? COPY.es;
}

export function getAllergenLabel(locale: string, code: string): string {
  return ALLERGEN_LABELS[locale]?.[code] ?? ALLERGEN_LABELS.en?.[code] ?? code.replaceAll("_", " ");
}
